name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      # Use the same make target both locally and on CI to make it easier to debug failures.
      - run: make docs
      # If markdownlint fixes issues, files will be changed. If so, fail the build.
      - run: git diff --exit-code
      # Upload the site so reviewers see it.
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site
          if-no-files-found: error
      - uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.repository == 'argoproj/argo-workflows' && github.ref == 'refs/heads/master'
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
